#!/bin/sh

if [ ! -f admin/deploy ]; then
  echo I think you are running this from the wrong place
  exit 1 
fi

to=$1

if test "$to" = "" ; then
  echo 'What hostname?'
  exit 1
fi

# rsync -avvR admin/run-js-tests *.go */*.go */*/*.go root@${to}:/root/go/src/github.com/sandhawke/mapleseed

P=src/github.com/sandhawke/mapleseed
cd $GOPATH
rsync -avvR $P/admin/run-js-tests $P/*.go $P/*/*.go $P/*/*/*.go root@${to}:/root/go

# beward importing something from sandhawke but not copying it in yet,
# because then "go get" will pull it from github
echo "building, testing, installing..."
ssh root@${to} "cd go/src/github.com/sandhawke/mapleseed && go get -v && go build && go test ./data/... && go test -v && go install && supervisorctl restart mapleseed"
